#!/usr/bin/env python3
"""
Load processed JSON files into a separate ChromaDB for Developmental Disability papers.

This script reads the JSON files generated by ingest_golden_references_advanced.py
and loads them into a dedicated ChromaDB instance to avoid segmentation faults
and keep the data isolated.

Usage:
    poetry run python scripts/load_json_to_chromadb_dd.py
"""

import json
import sys
from pathlib import Path
from typing import List, Dict
import numpy as np
import chromadb
from chromadb.config import Settings
from tqdm import tqdm

# Add project root to path
sys.path.append(str(Path(__file__).parent.parent))


def load_json_files(json_dir: Path) -> List[Dict]:
    """Load all JSON files from directory."""
    json_files = sorted(json_dir.glob("*.json"))
    papers = []
    
    print(f"Found {len(json_files)} JSON files")
    
    for json_file in tqdm(json_files, desc="Loading JSON files"):
        try:
            with open(json_file, 'r') as f:
                paper_data = json.load(f)
                papers.append(paper_data)
        except Exception as e:
            print(f"Error loading {json_file.name}: {e}")
    
    return papers


def create_chromadb_collections(db_path: str = "chromadb_data_dd"):
    """Create ChromaDB collections for developmental disability papers."""
    
    print(f"\nInitializing ChromaDB at {db_path}...")
    client = chromadb.PersistentClient(path=db_path)
    
    # Create collections for each RAPTOR level
    collection_l0 = client.get_or_create_collection(
        name="dd_papers_L0",
        metadata={"description": "Level 0: Original chunks from developmental disability papers"}
    )
    
    collection_l1 = client.get_or_create_collection(
        name="dd_papers_L1",
        metadata={"description": "Level 1: Section summaries from developmental disability papers"}
    )
    
    collection_l2 = client.get_or_create_collection(
        name="dd_papers_L2",
        metadata={"description": "Level 2: Paper summaries from developmental disability papers"}
    )
    
    print("✓ Collections created")
    
    return client, collection_l0, collection_l1, collection_l2


def load_papers_to_chromadb(
    papers: List[Dict],
    collection_l0,
    collection_l1,
    collection_l2
):
    """Load papers into ChromaDB collections."""
    
    total_l0 = 0
    total_l1 = 0
    total_l2 = 0
    
    for paper in tqdm(papers, desc="Loading papers to ChromaDB"):
        paper_id = paper['paper_id']
        
        try:
            # Load L0 chunks
            if paper['level0_chunks']:
                chunks = paper['level0_chunks']
                
                ids = [chunk['chunk_id'] for chunk in chunks]
                embeddings = [chunk['embedding'] for chunk in chunks]
                documents = [chunk['content'] for chunk in chunks]
                
                # Inject paper_title into metadata if missing
                metadatas = []
                for chunk in chunks:
                    meta = chunk['metadata'].copy()
                    if 'paper_title' not in meta:
                        meta['paper_title'] = paper.get('title', 'Unknown Title')
                    metadatas.append(meta)
                
                # Add in batches to avoid memory issues
                batch_size = 100
                for i in range(0, len(ids), batch_size):
                    collection_l0.add(
                        ids=ids[i:i+batch_size],
                        embeddings=embeddings[i:i+batch_size],
                        documents=documents[i:i+batch_size],
                        metadatas=metadatas[i:i+batch_size]
                    )
                
                total_l0 += len(chunks)
            
            # Load L1 summaries
            if paper['level1_summaries']:
                summaries = paper['level1_summaries']
                
                ids = [node['node_id'] for node in summaries]
                embeddings = [node['embedding'] for node in summaries]
                documents = [node['content'] for node in summaries]
                metadatas = [node['metadata'] for node in summaries]
                
                collection_l1.add(
                    ids=ids,
                    embeddings=embeddings,
                    documents=documents,
                    metadatas=metadatas
                )
                
                total_l1 += len(summaries)
            
            # Load L2 summary
            if paper['level2_summary']:
                summary = paper['level2_summary']
                
                collection_l2.add(
                    ids=[summary['node_id']],
                    embeddings=[summary['embedding']],
                    documents=[summary['content']],
                    metadatas=[summary['metadata']]
                )
                
                total_l2 += 1
                
        except Exception as e:
            print(f"\n⚠️  Error loading {paper_id}: {e}")
            continue
    
    return total_l0, total_l1, total_l2


def main():
    """Main execution."""
    
    print("=" * 70)
    print("DEVELOPMENTAL DISABILITY PAPERS - JSON TO CHROMADB")
    print("=" * 70)
    
    # Paths
    json_dir = Path("data/reference_papers/processed_json")
    
    if not json_dir.exists():
        print(f"Error: JSON directory not found: {json_dir}")
        return
    
    # Load JSON files
    papers = load_json_files(json_dir)
    
    if not papers:
        print("No papers loaded. Exiting.")
        return
    
    print(f"\nLoaded {len(papers)} papers")
    
    # Create ChromaDB collections
    client, collection_l0, collection_l1, collection_l2 = create_chromadb_collections()
    
    # Load papers
    print("\nLoading papers to ChromaDB...")
    total_l0, total_l1, total_l2 = load_papers_to_chromadb(
        papers,
        collection_l0,
        collection_l1,
        collection_l2
    )
    
    # Summary
    print("\n" + "=" * 70)
    print("LOADING COMPLETE")
    print("=" * 70)
    print(f"✅ Papers loaded: {len(papers)}")
    print(f"\nChunks loaded:")
    print(f"  Level 0 (chunks): {total_l0}")
    print(f"  Level 1 (sections): {total_l1}")
    print(f"  Level 2 (papers): {total_l2}")
    print(f"  Total: {total_l0 + total_l1 + total_l2}")
    print(f"\n✓ ChromaDB saved to: chromadb_data_dd/")
    print("=" * 70)


if __name__ == "__main__":
    main()
