"""Lightweight mock LLM service used for local agent orchestration.

This mock keeps the unified pipeline functional inside constrained
CI/dev environments where real API keys may not be present.  It
implements the minimal surface required by the existing ResearchAgent
classes (string-based ``complete`` calls and optional embedding
requests) without attempting to mimic full provider behaviour.
"""

from __future__ import annotations

import asyncio
import random
import time
from dataclasses import dataclass
from types import SimpleNamespace
from typing import AsyncIterator, Iterable, List, Union

from src.services.llm.interface import LLMServiceInterface
from src.services.llm.types import LLMRequest, LLMResponse, ModelProvider


@dataclass
class _MockConfig:
    model_name: str = "mock-llm"
    provider: ModelProvider = ModelProvider.ANTHROPIC
    latency_ms: float = 120.0


class MockLLMService(LLMServiceInterface):
    """Deterministic mock LLM implementation.

    The mock accepts either raw prompt strings or structured
    :class:`LLMRequest` objects and returns small templated completions.
    This is sufficient for the current specialist agents, which mainly
    rely on symbolic logic but optionally fall back to ``self.llm`` to
    produce human-readable prose.
    """

    def __init__(self, config: _MockConfig | None = None):
        self.config = config or _MockConfig()

    async def complete(self, request: Union[str, LLMRequest]) -> SimpleNamespace:
        prompt = request if isinstance(request, str) else request.prompt
        await asyncio.sleep(self.config.latency_ms / 1000.0)

        summary = self._summarise_prompt(prompt)
        content = (
            "[MOCK COMPLETION]\n"
            f"Model: {self.config.model_name}\n"
            f"Summary: {summary}\n"
            "This output is generated by the local MockLLMService for "
            "testing purposes."
        )

        response = SimpleNamespace(
            content=content,
            model=self.config.model_name,
            provider=self.config.provider.value,
            tokens_used=min(len(prompt) // 4 + 20, 2048),
            latency_ms=self.config.latency_ms,
            cost=0.0,
            finish_reason="stop",
            metadata={"mock": True},
        )

        return response

    async def stream_complete(self, request: LLMRequest) -> AsyncIterator[str]:
        """Yield the completion in a couple of chunks to mimic streaming."""

        full = await self.complete(request)
        text = full.content
        midpoint = max(1, len(text) // 2)
        yield text[:midpoint]
        await asyncio.sleep(0.05)
        yield text[midpoint:]

    async def embed(self, text: str) -> List[float]:
        """Return a simple deterministic embedding."""

        random.seed(hash(text) % (2**32 - 1))
        return [random.random() for _ in range(16)]

    def _summarise_prompt(self, prompt: str, max_chars: int = 140) -> str:
        cleaned = " ".join(prompt.split())
        return cleaned[:max_chars] + ("…" if len(cleaned) > max_chars else "")


